### PR TITLE
Add more modifiers

### PR DESCRIPTION
**Pull request by tforkmann**
Adding more modifieres for more type safety...

More to come...

### CODE REVIEW

**Comment by Dzoukr** [comment]
Hi @tforkmann,

thanks for the PR! Just to fully understand - are these classes coming from DaisyUI or Tailwind itself?

**Comment by tforkmann** [comment]
Mostly tailwind modifiers. Do you want them in a different library?

**Comment by Dzoukr** [comment]
Yup. To be honest, I was thinking about creating my own wrapper library around Tailwind, but it would be so huge, that I rather fall back to the combination of Daisy strongly-typed classes with custom Tailwind strings.

If you would have enough time, you can create your own `Feliz.Tailwind` (which would be great 👍) but I would like to keep this library as tiny as possible.

**Comment by tforkmann** [comment]
💯
Closing the PR

**Comment by Dzoukr** [comment]
Anyway, thanks again and if you are going into `Feliz.Tailwind` - good luck! 😄

**Comment by tforkmann** [comment]
https://github.com/tforkmann/Feliz.Tailwind/
Init version…lots of modifiers missing

**Comment by tforkmann** [comment]
Had a boring 4 hours train ride…

**Comment by Dzoukr** [comment]
That's how most of OSS is born 😂

**Pull request closed without merging**
